sudo: required

services:
  - docker

env:
  - VERSION=1.0

before_install:
  - docker version
  - docker network create --driver=bridge --subnet=192.168.0.0/16 --opt="com.docker.network.driver.mtu=1450" --opt="com.docker.network.bridge.name=redd0" nanobox
  - ifconfig
  - sudo -H pip install awscli

script: sudo stdbuf -oL test/run_all.sh $VERSION
